# Generated by Django 3.1.6 on 2021-02-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_round', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('N', 'NORMAL'), ('I', 'IMAGE')], max_length=1)),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.question')),
            ],
        ),
    ]
